### ISSUE TITLE
exponential backoff for at_least_once! mode

### ISSUE THREAD

**Issue by mmmries** [mxenabled/action_subscriber#1]
Right now the <code>at_least_once!</code> mode is pretty naive in how it handles failures. If an error occurs we will just requeue the message endlessly.  If the error that occurs is not recoverable (ie. it tries to hit a service which is completely gone from the internet) then this message will get retried over and over in a tight loop.

I think a better default behavior would be to handle failures with an exponential backoff algorithm similar to [sidekiq](https://github.com/mperham/sidekiq/wiki/Error-Handling#automatic-job-retry).

This is not a feature built into RabbitMQ, but there are [ways to handle it client side](http://globaldev.co.uk/2014/07/back-off-and-retry-with-rabbitmq/). We could add this behavior as an additional middleware in a totally separate gem, but I think it would make sense to have this be the default.

**Comment by camkidman** [comment]
@mmmries -- It seems like we can just create a dead-letter-exchange as the queues are created, but I'm having trouble getting the messages to dead-letter. It might just be my understanding, but I also am not fully sure how the *at_least_once_spec.rb* fails messages and retries them. Is there something about `sleep 0.1` that causes a message to fail/retry or is this method just not entirely finished?

**Comment by mmmries** [comment]
@camkidman good to see you! (or at least your avatar)

`at_least_once!` currently works by calling [`env.reject`](https://github.com/moneydesktop/action_subscriber/blob/97eac8edf6367e6e671dd4028b9f1b493bee088a/lib/action_subscriber/middleware/env.rb#L47) if an error is raised while processing a message, if no errors are raised then it calls [`env.acknowledge`](https://github.com/moneydesktop/action_subscriber/blob/97eac8edf6367e6e671dd4028b9f1b493bee088a/lib/action_subscriber/middleware/env.rb#L35).

In the current test for at_least_once! mode it triggers this behavior by [raising an exception](https://github.com/moneydesktop/action_subscriber/blob/97eac8edf6367e6e671dd4028b9f1b493bee088a/spec/integration/at_least_once_spec.rb#L6) the first two times it receives a message. This is meant to simulate something like a database failure occurring while trying to process a message.

`sleep 0.1` is just giving some time for the message to get to rabbitmq and back to our subscriber which is running in a separate thread.

So that all works as-is right now, but I don't want to use that feature in production because sometimes an error can't be resolved by just retrying. For instance what if I queued up a message about a given use, but then that user got deleted from the database? When my subscriber tries to lookup that user it might fail and I don't want it to just keep retrying that job forever. So the backoff is meant to give our application several chances to process a message over the course of a good chunk of time, but eventually let the system give up on that message.

**Comment by camkidman** [comment]
@mmmries -- Thanks for the answer! Good to see you too! Wish I could've made it to UVRB the other day! Did you have your baby yet??

So I've been looking at this and I have a suggested implementation here, but I wanted to seek your opinion before I go too far on what might be the wrong direction. 

To handle the whole process, I suggest the following:

1. We create a single dead-letter exchange (DLX) and a single dead-letter queue when the at_least_once! mode is called. All queues using this mode will have that exchange set as their dead-letter exchange.
2. At the same time, we create a subscriber on a different process that binds to the dead-letter queue
3. When a message failed from any queue that has the "x-dead-letter-exchange" argument, it goes into the aforementioned DLX, to the dead-letter queue, and to the subscriber we created.
4. The subscriber handles the message appropriately (it will have to pull a message off the queue, decide whether or not it's time to re-queue it to the original queue, modify the expiration header if so, then re-queue it).

[Here's a picture of a little diagram I drew to illustrate if I didn't communicate right](https://www.evernote.com/shard/s27/sh/737f9c4c-d080-4e9a-a3af-3d75630398c3/338b9ccd0c61e015d39ead7b76fed4bb)

Some considerations that I haven't fully flushed out and was wondering if you had input on:
- **Ideally we'd want the dead-letter queue to be a priority queue so the subscriber for the DLQ grabs the messages in the order they have to be sent. I didn't see anything that would handle this except for [this plugin](https://github.com/rabbitmq/rabbitmq-priority-queue), but do we want users of this gem to have to install it?**
- If we don't use the priority queue plugin, our subscriber would need to determine whether or not the message needed to be sent based on some criteria, probably manipulating the expiration header. But we don't want the subscriber to hold onto the message for the duration of the expiration.
- Seems like, in this circumstance, the subscriber to the DLQ is the one that handles the exponential backoff.

Just wanted to see what your thoughts were before I get too far down a path that I'm not sure is right.

**Comment by mmmries** [comment]
Cameron - 
Sorry for the slow response on this. I'm having my baby today and spent last week trying to make sure I wasn't leaving any loose ends at work. I don't think we should need the priority queue for our waiting queue. I think we can let RabbitMQ handle which messages get re-published by just having a timeout set on each message when we publish it into the waiting queue.

I'll try to draw out what I'm thinking and attach it here when a have a little time.

**Comment by mmmries** [comment]
![screen shot 2015-02-16 at 2 55 09 pm](https://cloud.githubusercontent.com/assets/80008/6219829/d5f046a2-b5eb-11e4-8b3b-091345a0b121.png)

Here's a quick summary of what I'm thinking: basically when the subscriber decides that a job has failed and needs to retry it publishes a new copy of the message to the `retries` exchange. The new copy of the messages looks the same as the original, except that it has a TTL header. The timeouts queue will bind to the retries exchange such that it gets a copy of every message, that way we can publish the message with the right routing key and set the dead-letter-exchange for the timeouts queue to go back to the events exchange. That way once the message times out it will get re-published and our subscriber will see the message again.

**Comment by mmmries** [comment]
@camkidman just as a reminder, I totally don't expect you to be spending your personal time on this. I do personally believe that contributing to open source is a great way to showcase your engineering skills and communication skills in a way that can be evaluated by any potential employers, but you can feel free to ditch this project at any time and for any reason.

With that said, I had a little time the other night to [spike out a rough idea of how this might all work at a code level](https://github.com/moneydesktop/action_subscriber/compare/master...at_least_once_backoff). That branch is definitely too ugly to be considered ready to merge into this project, but it shows the general idea. Currently it passes all tests under MRI, but fails under jRuby (no idea why yet).

It works something like this:

1) When someone calls `at_least_once!` in a subscriber it sets up the `retries` exchange (as a topic exchange) and sets up the `timeouts` queue which receives a copy of any message sent to the `retries` exchange and always publishes its dead letters back to the `events` exchange.

2) When a message raises an unhandled error in an `at_least_once!` subscriber, the subscriber publishes a copy of that message to the retries queue with the same payload, headers, and routing key as the original message, but we add a TTL header to it.

3) When the message times out in the timeouts queue it gets sent back to the `events` exchange and ends up back in the subscriber code again.

I think that general flow will work for this problem, but it leaves several details unaddressed:

* Can the user change the retry schedule? Currently the system waits 300ms, 900ms, 2.7sec, 8.1sec all the way up to a one day wait and then finally just chucks the message out the door.

* Should we log some details when a message gets chucked out the door? In theory this should almost never happen, but in practice I'm sure it will happen sometimes and it would probably be good to report those cases back to the user so that they can address them in their system.

* Right now all messages go back to the "events" exchange, but the user may not be using the "events" exchange. They can pick their own exchange. So what if the message needs to go back to a different exchange? What if the user has multiple exchanges they are receiving messages from?

* All of the naming in my spike branch is pretty terrible

**Comment by camkidman** [comment]
@mmmries -- Thanks for the disclaimer! I very much would like to start contributing to open source projects like this. I don't get as much code exposure as I'd like on a day-to-day basis, so this is actually fun for me (although I'm finding myself with less time to work on this specifically, I'd still like to contribute however I can).

If I may offer some opinions on the issues:

-- Do we want to build in the ability for users to change the retry schedule? I think as a default behavior, this is better than it was. I would say "this is how it behaves by default when you call at_least_once!" And I can't imagine very many users being unhappy with that.

-- I definitely think something should be logged when a message is completely discarded. You can never have too much logging, in my experience

-- I would say this is quite the issue. We could always re-publish the message to the exchange that it originally came from, but if any link in the chain isn't there anymore that would pose an issue, wouldn't it?

-- The naming isn't *that* bad

I hope all is well with your newborn!!

**Comment by mmmries** [comment]
This has been added and is the default behavior for `at_least_once!` subscribers
