### ISSUE TITLE
Extract action_subscriber-bunny and action_subscriber-march_hare

### ISSUE THREAD

**Issue by mmmries** [mxenabled/action_subscriber#10]
After chatting with @localshred the other day about the `protobuf` gem and where it's headed it occurred to me that releasing both a `java` and `mri` version of this gem might be silly.

Most of the [ugliest](https://github.com/moneydesktop/action_subscriber/blob/c220f137046ee78fb4722f52c99d432edcaf8c54/action_subscriber.gemspec#L23) [parts](https://github.com/moneydesktop/action_subscriber/blob/c220f137046ee78fb4722f52c99d432edcaf8c54/lib/action_subscriber/rabbit_connection.rb#L10) of [this gem](https://github.com/moneydesktop/action_subscriber/blob/c220f137046ee78fb4722f52c99d432edcaf8c54/lib/action_subscriber/base.rb#L6) right now are the areas where we have to handle the differences between `bunny` and `march_hare`.

I have also been asked by a few people at URUG meetups and MWRC whether ActionSubscriber could support other message queuing services like NSQueue.

So I'm thinking about making a `action_subscriber-bunny` gem which would have all the bunny specific stuff in it and would `add_runtime_dependency 'action_subscriber', '~> 2.0'`. What do other people think?

**Comment by aemadrid** [comment]
Sounds like a good idea. It's sad that bunny and march_hare are so similar but so different in small ways that you have to go out of your way to use them both. I'm also really liking NSQ so making AS be queue independant sounds like a win to me.

**Comment by mmmries** [comment]
this has been out there for a while as an idea, but we just don't need this feature so unless someone else wants to put some effort into this we are going to table the idea
