### ISSUE TITLE
Open Source `harness-action_subsriber`

### ISSUE THREAD

**Issue by mmmries** [mxenabled/action_subscriber#26]
We have an internal gem hooking up the `ActiveSupport` instrumentation in `action_subscriber` to the harness gem so it can easily be forwarded onto a statsd server.

We should open source that gem.

**Comment by liveh2o** [comment]
:+1:

**Comment by mmmries** [comment]
Donezo! :ballot_box_with_check: 

https://github.com/mxenabled/harness-action_subscriber
