### ISSUE TITLE
Multiple threadpools

### ISSUE THREAD

**Issue by mmmries** [mxenabled/action_subscriber#37]
I would really like to deprecate the `--allow-low-priority-queues` option. Running two separate subscriber processes is a pain when what we really want is just to avoid having the low priority work take up all the threads in the threadpool.

I propose that we make it possible to assign a `route` to a named threadpool. This would allow us to setup a `low_priority` threadpool with just a few threads and connect all the `*_low` subscriptions to that threadpool while we keep the rest of the subscriptions connected to the main threadpool.

`config/action_subscriber.yml`
```yaml
production:
  threadpool_size: 10 #the simpler form (will still be supported)
  threadpool_sizes:
    default: 10
    low_priority: 5
```

`config/initializers/action_subscriber.rb`
```ruby
ActionSubscriber.draw_routes do
  route ::ClientSnapshotSubscriber, :created, :acknowledgements => true, :publisher => :amigo
  route ::AggregationSubscriber, :completed_low, :threadpool => :low_priority, :acknowledgements => true, :publisher => :grunt
end
```

Or perhaps we could skip the yaml configuration and just set things up in the route definitions like:

```ruby
low_priority_threadpool = ::ActionSubscriber::Threadpool.new(5)

::ActionSubscriber.draw_routes do
  route ::ClientSnapshotSubscriber, :created, :acknowledgements => true, :publisher => :amigo
  route ::AggregationSubscriber, :completed_low, :threadpool => low_priority_threadpool, :acknowledgements => true, :publisher => :grunt
end
```

/cc @abrandoned @localshred @liveh2o @brianstien

**Comment by abrandoned** [comment]
can things go to 2 threadpools? ... today the _low queue takes things from *_low or (if no work is there) from the non *_low queues .... should we be using priority in some way? https://www.rabbitmq.com/priority.html

I really like the idea of having 1 process and multiple threadpools

**Comment by mmmries** [comment]
That rabbitmq priority thing was an optional extension until `3.5.0` so I'm glad they pulled it into the core. We are running `3.5.3` in production so we could use that instead of making `_low` queues. The problem is that we would have to delete and re-create a queue in order to support priority queues. Rabbit won't let us switch at runtime.
