### ISSUE TITLE
Surprising Retry Behavior

### ISSUE THREAD

**Issue by mmmries** [mxenabled/action_subscriber#42]
In talking with @abrandoned about a similar system I realized that if you have two subscribers that are both listening to the same routing key, and one of them fails a job and retries it (with the new `at_least_once!` mode), the job would be re-published to both of the subscribers.

This seems like a very surprising behavior to me. I think each of those subscribers should be able to set themselves as `at_least_once!`, `at_most_once!` or have no acknowledgements at all without worrying about whether the other subscribers are going to re-publish the message.

Is there a way for us to setup the `at_least_once!` behavior so that it re-queues the message just to one subscriber's queue rather than re-publishing it to the exchange (and giving a copy to all of the subscribers listening to that routing key)?

**Comment by liveh2o** [comment]
I agree, this is surprising behavior. Subscribers should be able to retry without affecting other subscribers.
