### ISSUE TITLE
Add Rails style before/around/after filters

### ISSUE THREAD

**Issue by liveh2o** [mxenabled/action_subscriber#55]
Rails provides a nice filter DSL for running code [before, around, or after actions](http://guides.rubyonrails.org/action_controller_overview.html#filters). I think it would be a cool feature to add here as well. Doing so would provide a nice way of supporting a `rescue_from` DSL that [Rails provides as well](http://guides.rubyonrails.org/action_controller_overview.html#rescue).

**Comment by liveh2o** [comment]
Looks like this was partially added in #8. It supports around filters, but not before/after filters.

**Comment by mmmries** [comment]
`around` filters were added and we haven't had any more interest in `before` or `after` filters so I'm going to close this for now.
