### ISSUE TITLE
Handle a subscriber being removed if it is still in routes

### ISSUE THREAD

**Issue by ryanbjones** [mxenabled/action_subscriber#60]
I deleted a subscriber and after a couple of hours we realized that none of the subscribers at all were running. This is because I had forgotten to delete the subscriber from the routes and so upon initialization it would blow up. I think this should be handled gracefully

**Comment by ryanbjones** [comment]
I'll look into this, but wanted to document it in case I get sidetracked

**Comment by mmmries** [comment]
Interesting... I'm curious to see what you come up with. As far as I know this would cause the process to exit immediately with an error message and the error message should be something like `Unitialized constant MemberSubscriber` which I think is a pretty good error message in this case.

If someone tries to subscribe to something that doesn't exist I think that blowing up and raising an error is a pretty good thing to do, but I'm curious to see what you're proposal for gracefully handling it would look like.

**Comment by film42** [comment]
I think this is something we need to handle as part of MX's deploy process and not something that needs to be resolved as part of ActionSubscriber. If your app does not start and the deploy succeeds, then that's probably not a good thing.
