### ISSUE TITLE
Broken Test: ActionSubscriber, JRuby and acknowledges

### ISSUE THREAD

**Issue by mmmries** [mxenabled/action_subscriber#61]
I recently received the following email from a user and wanted to provide an answer to any other people using ActionSubscriber.

----------------------------------

Hello Michael,

I kindly ask for help with using ActionSubscriber. I'm making a RoR-application that gets messages from RabbitMq, saves them into DB, and sends a manual acknowledgement after successfull saving or a reject if an error occurs.
I also have a test for this code. Both the code and the test worked pretty well in MRI 2.2.2. After switching the project into JRuby 9.0.4.0 or 9.0.5.0 where ActionSubriber uses MarchHare instead of Bunny the program still works well, but the test does not work anymore. I tried several latest versions of MarchHare and ActionSubscriber, but the problem persists. Am I doing something wrong? The test fails on sending acknowledgement with this backtrace:

```
Error processing message: #method<channel.close>(reply-code=200, reply-text=Goodbye, class-id=0, method-id=0)
Backtrace: /home/dzenovich/.rvm/gems/jruby-9.0.4.0@lochness/gems/march_hare-2.16.0-java/lib/march_hare/exceptions.rb:121:in `convert_and_reraise'
/home/dzenovich/.rvm/gems/jruby-9.0.4.0@lochness/gems/march_hare-2.16.0-java/lib/march_hare/channel.rb:976:in `converting_rjc_exceptions_to_ruby'
/home/dzenovich/.rvm/gems/jruby-9.0.4.0@lochness/gems/march_hare-2.16.0-java/lib/march_hare/channel.rb:748:in `basic_ack'
/home/dzenovich/.rvm/gems/jruby-9.0.4.0@lochness/gems/march_hare-2.16.0-java/lib/march_hare/channel.rb:663:in `block in ack'
org/jruby/RubyProc.java:318:in `call'
/home/dzenovich/.rvm/gems/jruby-9.0.4.0@lochness/gems/march_hare-2.16.0-java/lib/march_hare/channel.rb:991:in `guarding_against_stale_delivery_tags'
/home/dzenovich/.rvm/gems/jruby-9.0.4.0@lochness/gems/march_hare-2.16.0-java/lib/march_hare/channel.rb:662:in `ack'
/home/dzenovich/.rvm/gems/jruby-9.0.4.0@lochness/gems/action_subscriber-2.2.1-java/lib/action_subscriber/middleware/env.rb:45:in `acknowledge'
/home/dzenovich/.rvm/gems/jruby-9.0.4.0@lochness/gems/action_subscriber-2.2.1-java/lib/action_subscriber/base.rb:60:in `acknowledge'
...
```

Here is my subscriber:
```ruby
class MySubscriber < ::ActionSubscriber::Base
  manual_acknowledgement!

  def created
    data = JSON.parse(payload)

    # skip messages without id field

    unless data["id"]
      acknowledge
      return
    end 

    delivery_tag = env.instance_variable_get(:@delivery_tag)
    unless delivery_tag.is_a? Fixnum
      delivery_tag = delivery_tag.tag
    end 
    id_str = data["id"]
    document = MyModel.where(_id: id_str,
                             delivery_tag: delivery_tag,
                             state: 'pending').first
    document ||= MyModel.new _id: id_str,
                             payload: payload,
                             delivery_tag: delivery_tag,
                             state: 'pending'
    if document.save
      acknowledge
      document.update(state: 'commited')
    else
      reject
    end 
  end 
end
```
My initializer for ActionSubscriber (config/initializers/action_subscriber.rb):
```ruby
ActionSubscriber.draw_routes do
  route MySubscriber, :created,
        exchange:         'events',
        acknowledgements: true
end

ActionSubscriber.configure do |config|
  config.hosts = ["localhost"]
  config.port = 5672
  config.error_handler = lambda do |error, env_hash|
    Rails.logger.error("Error processing message: #{error.message}\n"\
                       "Backtrace: #{error.backtrace.join("\n")}")
    raise error
  end 
end

unless defined?(Rails::Console) or Rails.env.test?
  ActionSubscriber.start_subscribers
end
```

My test/test_helper.rb:
```ruby
ENV["RAILS_ENV"] ||= "test"
require File.expand_path('../../config/environment', __FILE__)
require 'rails/test_help'

class ActiveSupport::TestCase
  def before_setup
    DatabaseCleaner.start

    $messages = Set.new
    draw_routes if respond_to?(:draw_routes)
    ::ActionSubscriber::RabbitConnection.subscriber_connection
    ::ActionSubscriber.setup_queues!

    super
  end 

  def after_teardown
    super

    ::ActionSubscriber.stop_subscribers!
    ::ActionSubscriber::RabbitConnection.subscriber_disconnect!
    ::ActionSubscriber.instance_variable_set("@route_set", nil)

    DatabaseCleaner.clean
  end 
end

require 'mocha/mini_test'
```

Here is my test:

```ruby
  def test_real_publishing
    successful_payload = "{"id": 12345}"
    assert_difference("MyModel.count", 1) do
      ActionSubscriber::Publisher.publish(route_tag,
                                          successful_payload, 'events')
      ActionSubscriber::auto_pop!
    end 
  end
```
Thanks in advance.

**Comment by mmmries** [comment]
First off I just want to say, "YAY!" :heart_eyes: :tada: :balloon: 

I'm so glad people use this library and have been able to use it to switch between MRI and jRuby. It has been a lot of work to try to make that possible so I'm really happy that is has been useful.

Secondly I want to say sorry for these lines of code: 
```ruby
  delivery_tag = env.instance_variable_get(:@delivery_tag)
    unless delivery_tag.is_a? Fixnum
      delivery_tag = delivery_tag.tag
    end 
```

I haven't made much use of delivery tags in my apps so I didn't notice that they were different on MRI vs jRuby. I'll try to make that better in the future.

Lastly I think I might know what is wrong with the test. `ActionSubscriber::Publisher.publish` is asynchronous by default. RabbitMQ defaults to a behavior where as soon as you send the bytes of your message down the socket it returns immediately. This means that calling `publish` and then immediately calling `auto_pop!` has a sort of race condition happening.

That error message in your output looks like the channel was closed when you tried to acknowledge the message. This can sometimes happen if a message tries to get acknowledged twice, or if you try to acknowledge a delivery tag that doesn't belong to the current channel. If you can post a few more lines of the backtrace I can help nail down where the second acknowledge is coming from.

**Comment by zenovich** [comment]
@mmmries, thanks a lot for making ActionSubscriber as well as for your reply. The line causing the error (the bottom line of the backtrace) is the line with 'acknowledge' of this one code-block of my subscriber:
```ruby
   if document.save
      acknowledge
      document.update(state: 'commited')
    else
      reject
    end 
```

**Comment by mmmries** [comment]
@zenovich I also noticed that you are using `jruby-9.0.4.0` in your test. Do you mind trying it with `jruby-9.0.1.0`? I know at MX we rolled back to `jruby-9.0.1.0` because of some threaded issues around regex and they seemed to be affecting `march_hare` specifically.

Not sure if that will fix it, but worth a try.

**Comment by zenovich** [comment]
Hi @mmmries,

I tried jRuby 9.0.1.0 and the test doesn't work there as well.
Anyway, I have some progress with this. I've removed all lines in 'after_teardown' method:
```ruby
 def after_teardown
    super

#::ActionSubscriber.stop_subscribers!
#    ::ActionSubscriber::RabbitConnection.subscriber_disconnect!
#    ::ActionSubscriber.instance_variable_set("@route_set", nil)

    DatabaseCleaner.clean
  end
```
Then I've added sleeps before publishing and after calling 'auto_pop!'. Next I've used ActivePublisher for publishing test messages. So the test now is this one:

```ruby
  def test_real_publishing
    ActivePublisher.configure do |config|
      config.host = "localhost"
      config.port = 5672
      config.publisher_confirms = true
    end 
    assert_difference("#{document_class.name}.count", 1) do
      ActivePublisher.publish(route_tag,
                              successful_payload, 'events')
      sleep 0.5 
      ActionSubscriber::auto_pop!
      sleep 0.5 
    end 
  end
```
It works stably now even in jRuby 9.0.5.0. The last problem I have here is that the test-suite hangs on exiting after displaying this message: "Draining async publisher in-memory adapter queue before shutdown. Current queue size: 0."

**Comment by mmmries** [comment]
@zenovich If you switch back to using `ActionSubscriber::Publisher.publish` for publishing your test message I think it should fix your hanging test problem. `ActivePublisher` hasn't released any public versions yet because we are still working through some of the details of how to handle `at_exit` hooks that will cleanup the threadpool that connects to rabbitmq

**Comment by mmmries** [comment]
BTW I'm glad that the `sleep`s seem to make your test more stable. I'm sure you've already noticed, but for others reading this thread later we use a pattern in most of our end-to-end tests in ActionSubscriber where we have a test like: 

```ruby
    it "routes messages to the right place" do
      ::ActionSubscriber.auto_subscribe!
      ::ActionSubscriber::Publisher.publish("basic_push.booked", "Ohai Booked", "events")

      verify_expectation_within(2.0) do
        expect($messages).to eq(Set.new(["Ohai Booked"]))
      end
    end
```

The `verify_expectation_within(2.0)` call will check a verification a whole bunch of times for up to 2 seconds before it fails the test. That way the test completes quickly when you are on a warm system, but it can wait for up to 2 seconds to complete when running on a CI server where the asynchronous publishing and receiving is much slower.

```ruby
def verify_expectation_within(number_of_seconds, check_every = 0.02)
  waiting_since = ::Time.now
  begin
    sleep check_every
    yield
  rescue RSpec::Expectations::ExpectationNotMetError => e
    if ::Time.now - waiting_since > number_of_seconds
      raise e
    else
      retry
    end
  end
end
```

**Comment by film42** [comment]
Maybe MarchHare is delaying the send, because:

`::ActionSubscriber::Publisher.publish` should be synchronous.

`::ActionSubscriber::Publisher.publish_async` is async (calls to `.publish`).

**Comment by zenovich** [comment]
@mmmries, The question about tests hanging on exiting is still open.

**Comment by mmmries** [comment]
@zenovich I'm happy to keep debugging this problem. It sounded to me like the conversation had died down. Have you tried switching back to publishing with `ActionSubscriber::Publisher`? Or maybe if you switch to use the `0.1.3` version of ActivePublisher (just released today) it might fix the hanging test.

Let us know if it doesn't get fixed and we can keep trying to help

**Comment by zenovich** [comment]
I tried to switch tests back to using ActionSubscriber::Publisher and to upgrade ActivePublisher as well. None of these options helps.

The root of the problem is that Rake loads Rails environment twice, so the in-memory publisher is initialized twice as well, and then one of the environments is unloaded, so one of the in-memory publishers is shut down before tests. I suppose this publisher's shutdown causes the problem. The log of my tests looks like this:

```
$ bundle exec rake test
I, [2016-04-04T14:59:34.406000 #14431]  INFO -- : Starting in-memory publisher adapter.
I, [2016-04-04T14:59:54.161000 #14481]  INFO -- : Starting in-memory publisher adapter.
I, [2016-04-04T14:59:59.372000 #14481]  INFO -- : Draining async publisher in-memory adapter queue before shutdown. Current queue size: 0.
Run options: --seed 53468

# Running:

...

Finished in 15.811167s, 0.5692 runs/s, 0.5692 assertions/s.

9 runs, 9 assertions, 0 failures, 0 errors, 0 skips

I, [2016-04-04T15:00:16.367000 #14431]  INFO -- : Draining async publisher in-memory adapter queue before shutdown. Current queue size: 0.
```
At this point the process hangs forever.

**Comment by mmmries** [comment]
@zenovich interesting. I've been using rspec and invoking my application tests directly. I'll try to invoke with `rake` and see if I can reproduce

**Comment by mmmries** [comment]
Hmmm, I just ran my app's test suite and it started the async publisher twice, but they both shut down when the test suite completed. I don't think my test suite actually exercises the publisher though. I'll try to add a test that does a publish to see if that causes the hanging.

**Comment by zenovich** [comment]
The problem disappeared after adding these lines into tests' teardown method:
```ruby
  ::ActionSubscriber.stop_subscribers!
  ::ActionSubscriber::RabbitConnection.subscriber_disconnect!
  ::ActionSubscriber.instance_variable_set("@route_set", nil)
```
The cause of the problem was in active rabbitmq connection.

**Comment by mmmries** [comment]
@zenovich oh, that makes sense! I wonder if we should add the `subscriber_disconnect!` to our current `at_exit` block. https://github.com/mxenabled/action_subscriber/blob/4d12140fddc49bbec3f3c38043a706fd2888b77d/lib/action_subscriber.rb#L135-L138

**Comment by mmmries** [comment]
Looks like this was resolved
