### ISSUE TITLE
issue requiring actionsubscriber/rspec when using rspec-rails gem

### ISSUE THREAD

**Issue by asjaeger** [mxenabled/action_subscriber#94]
Ran into a problem when using rspec-rails gem instead of just rspec.

```
/Users/aj/.rvm/gems/ruby-2.3.3@alfred/gems/action_subscriber-4.5.1/lib/action_subscriber/rspec.rb:1:in 'require': cannot load such file -- rspec (LoadError)
  from /Users/aj/.rvm/gems/ruby-2.3.3@alfred/gems/action_subscriber-4.5.1/lib/action_subscriber/rspec.rb:1:in '<top (required)>'
  from /Users/aj/Projects/alfred/spec/spec_helper.rb:1:in 'require'
  from /Users/aj/Projects/alfred/spec/spec_helper.rb:1:in '<top (required)>'
  from /Users/aj/.rvm/gems/ruby-2.3.3@alfred/gems/rspec-core-3.7.0/lib/rspec/core/configuration.rb:1455:in 'require'
  from /Users/aj/.rvm/gems/ruby-2.3.3@alfred/gems/rspec-core-3.7.0/lib/rspec/core/configuration.rb:1455:in 'block in requires='
  from /Users/aj/.rvm/gems/ruby-2.3.3@alfred/gems/rspec-core-3.7.0/lib/rspec/core/configuration.rb:1455:in 'each'
  from /Users/aj/.rvm/gems/ruby-2.3.3@alfred/gems/rspec-core-3.7.0/lib/rspec/core/configuration.rb:1455:in 'requires='
  from /Users/aj/.rvm/gems/ruby-2.3.3@alfred/gems/rspec-core-3.7.0/lib/rspec/core/configuration_options.rb:112:in 'block in process_options_into'
  from /Users/aj/.rvm/gems/ruby-2.3.3@alfred/gems/rspec-core-3.7.0/lib/rspec/core/configuration_options.rb:111:in 'each'
  from /Users/aj/.rvm/gems/ruby-2.3.3@alfred/gems/rspec-core-3.7.0/lib/rspec/core/configuration_options.rb:111:in 'process_options_into'
  from /Users/aj/.rvm/gems/ruby-2.3.3@alfred/gems/rspec-core-3.7.0/lib/rspec/core/configuration_options.rb:21:in 'configure'
  from /Users/aj/.rvm/gems/ruby-2.3.3@alfred/gems/rspec-core-3.7.0/lib/rspec/core/runner.rb:99:in 'setup'
  from /Users/aj/.rvm/gems/ruby-2.3.3@alfred/gems/rspec-core-3.7.0/lib/rspec/core/runner.rb:86:in 'run'
  from /Users/aj/.rvm/gems/ruby-2.3.3@alfred/gems/rspec-core-3.7.0/lib/rspec/core/runner.rb:71:in 'run'
  from /Users/aj/.rvm/gems/ruby-2.3.3@alfred/gems/rspec-core-3.7.0/lib/rspec/core/runner.rb:45:in 'invoke'
  from /Users/aj/.rvm/gems/ruby-2.3.3@alfred/gems/rspec-core-3.7.0/exe/rspec:4:in '<top (required)>'
  from /Users/aj/.rvm/gems/ruby-2.3.3@alfred/bin/rspec:23:in 'load'
  from /Users/aj/.rvm/gems/ruby-2.3.3@alfred/bin/rspec:23:in '<main>'
  from /Users/aj/.rvm/gems/ruby-2.3.3@alfred/bin/ruby_executable_hooks:15:in 'eval'
  from /Users/aj/.rvm/gems/ruby-2.3.3@alfred/bin/ruby_executable_hooks:15:in '<main>'
```

I found that this is due to the 
`require 'rspec'` line in `/lib/action_subscriber/rspec.rb` 
Once I commented out that line my rspecs were working perfectly. I also tested it on a branch that had the rspec gem to make sure it still worked. Here is a PR for your consideration. https://github.com/mxenabled/action_subscriber/pull/93

I also threw in a tiny change in your readme that is also related to rspec.

**Comment by mmmries** [comment]
Hmmm, that's an odd issue. I would have thought that `require "rspec"` would have just been skipped in a `spec_helper.rb` since the gem has probably already been loaded...

I'm looking at one of my projects from work and we are using `rspec-rails` along with this gem and they load fine. We load them in this order right now:

```
require ::File.expand_path("../../config/environment", __FILE__)
require "rspec/rails"
require "powerpak/rspec"
require "protobuf/rspec"
require "action_subscriber/rspec"
require "sidekiq/testing"
```

This branch appears to work fine on my project so I'm :+1: with using it, but I'd like to understand what is breaking. @asjaeger can you provide any details about your `spec_helper`, ruby version, rails version, bundle version etc?

@film42 any concerns from you with removing that `require "rspec"`?

**Comment by film42** [comment]
@mmmries the PR seems fine to me.

I'm guessing you don't have `rspec` in your gemfile? Looks like `rspec-rails` pulls in components (not the full `rspec` gem [which contains an `rspec.rb` file](https://github.com/rspec/rspec/blob/master/lib/rspec.rb)). I'll give that a 0/10 for disoverability.

Maybe instead of deleting `require "rspec"` we should change it to `require "rspec/core"`?

**Comment by mmmries** [comment]
@asjaeger do you want to try with `require "rspec/core"` in this branch and see if it works for your application?

**Comment by film42** [comment]
Just released version 5.0.1. I'm going to close this issue, but please re-open if this problem continues to happen! Thank you so much for the help @asjaeger ❤️ !

**Comment by mmmries** [comment]
🎉 💥  Thanks @asjaeger and @film42 ⚡️ 💛 💙 💚

**Comment by asjaeger** [comment]
Awesome, Thanks guys!! sorry about my lack of communication on this issue as I put my response in the PR. I appreciate the help with this issue! @mmmries @film42 You guys rock 🍻 . Sorry I didn't update the version in my PR. I thought about it but totally forgot when I put the PR up.

**Comment by film42** [comment]
NP @asjaeger !!! We usually wait until we've merged into master before bumping the version unless it's a pre-release.
